[package]
name = "hips"
version = "0.1.0"
authors = ["Louis Feuvrier <mqnfred@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1"
base64 = "^0"
# TODO: once published to crates.io, use 3.0.0 there
clap = { git = "https://github.com/clap-rs/clap/" }
clishe = "^0"
openssl = { version = "0.10", features = ["vendored"] }
paste = "^0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "^1"
serde_yaml = "0.8"
snailquote = "^0"
tinytemplate = "^1"
