[package]
name = "hips"
version = "0.1.0"
authors = ["Louis Feuvrier <mqnfred@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1"
base64 = "^0"
# TODO: we should just track "^3" (not available atm for some reason)
clap = { git = "https://github.com/clap-rs/clap", branch = "master" }
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
